const apartmentSale = {
  author: 'required',
  key: 'required',
  company: 'required',
  created: 'required',
  modified: 'required',
  type: 'required',
  object: 'required',
  price: 'required',
  agent_pay: 'optional',
  images: 'optional',
  description: 'optional',
  locality: 'required',
  localityType: 'required',
  localityId: 'optional',
  street: 'required',
  streetType: 'required',
  streetId: 'optional',
  building: 'required',
  buildingId: 'optional',
  buildingType: 'required',
  district : 'required',
  waymark: 'optional',
  building_type: 'required',
  material: 'required',
  rooms: 'required',
  floor: 'required',
  floors: 'required',
  area_full: 'required',
  area_living: 'required',
  area_kitchen: 'required',
  furnish: 'optional',
  bath: 'required',
  balcony: 'required'
}

export default apartmentSale;