const commercialSale = {
  author: 'required',
  key: 'required',
  company: 'required',
  created: 'required',
  modified: 'required',
  type: 'required',
  object: 'required',
  price: 'required',
  agent_pay: 'optional',
  images: 'optional',
  description: 'optional',
  locality: 'required',
  localityType: 'required',
  localityId: 'optional',
  street: 'required',
  streetType: 'required',
  streetId: 'optional',
  building: 'required',
  buildingId: 'optional',
  buildingType: 'required',
  district : 'required', 
  waymark: 'optional',
  commercial_retail: 'optional',
  commercial_office: 'optional',
  commercial_industrial: 'optional',
  commercial_warehouse: 'optional',
  commercial_business: 'optional',
  commercial_land: 'optional',
  commercial_apartments: 'optional',
  commercial_material: 'required',
  floor: 'required',
  special_floor: 'optional',
  floors: 'required',
  area_full: 'required',
  minimal_area: 'optional',
  line: 'optional',
  furnish: 'optional',
  planning: 'optional',
  ceilings_height: 'optional',
  power: 'optional',
  internet: 'optional',
  security_alarm: 'optional',
  fire_alarm: 'optional',
  shutters: 'optional',
  monument: 'optional',
  windows: 'optional',
  owner: 'optional'
}

export default commercialSale;