let cottageSale = {
  author: 'required',
  key: 'required',
  company: 'required',
  created: 'required',
  modified: 'required',
  type: 'required',
  object: 'required',
  price: 'required',
  agent_pay: 'optional',
  images: 'optional',
  description: 'optional',
  locality: 'required',
  localityType: 'required',
  localityId: 'optional',
  street: 'required',
  streetType: 'required',
  streetId: 'optional',
  building: 'optional',
  buildingId: 'optional',
  buildingType: 'optional',
  district: 'optional', 
  waymark: 'optional',
  cadastral_number: 'optional',
  distance: 'optional',
  direction: 'optional',
  cottage_type: 'required',
  cottage_area: 'required',
  material: 'required',
  rooms: 'required',
  floors: 'required',
  area_full: 'required',
  furnish: 'optional',
  cottage_gas: 'optional',
  cottage_power: 'optional',
  cottage_water: 'optional',
  cottage_sewer: 'optional',
  internet: 'optional',
  cottage_security: 'optional',
  cottage_forest: 'optional',
  cottage_entrance: 'optional',
  cottage_bus: 'optional',
}

export default cottageSale;